### ISSUE TITLE
is there any possible to public trainning and evaluation detail?

### ISSUE THREAD

**Issue by liwenssss** [penincillin/DCT_ICCV-2019#1]
Hi,great job for you.I read the paper.Since it can serve as a baseline, I want to know is there any possible to public your trainning and evaluation details?
Thx for your contribution!

**Comment by penincillin** [comment]
Thanks for your interest in our work.
Train code is highly likely to be released after CVPR 2020 deadline. (I cannot give you a guarantee right now, but I will work on that)
Thanks

**Comment by penincillin** [comment]
The code is highly likely to be released on early December 2019.

**Comment by liwenssss** [comment]
good news! can't wait~
