### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by liwenssss** [penincillin/DCT_ICCV-2019#3]
when I use "sh script/train_all_img.sh", I got an error like this:
```
COCODataset dataset has 35978 data
UP3DDataset dataset has 7126 data
Human36MDataset dataset has 43104 data
!!!!!!!!!!!! Attention, use one branch framework
Traceback (most recent call last):
  File "src/train_dist.py", line 135, in <module>
    main()
  File "src/train_dist.py", line 74, in main
    model = DCTModel(opt)
  File "/home/liwensh2/code/DCT_ICCV-2019/src/models/dct_model.py", line 121, in __init__
    self.smpl, device_ids=[torch.cuda.current_device()])
  File "/home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 288, in __init__
    self._ddp_init_helper()
  File "/home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 338, in _ddp_init_helper
    self.process_group)
RuntimeError: replicas_[0].size() >= 1 ASSERT FAILED at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:53, please report a bug to PyTorch. Expected at least one parameter. (Reducer at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:53)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f1e388cc441 in /home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/torch/lib/libc10.so)

...
```
can you give me any suggestion to solve it  ?

**Comment by penincillin** [comment]
Would you mind tell me the Pytorch Version, CUDA version and number of GPUs you use ?

**Comment by liwenssss** [comment]
> Would you mind tell me the Pytorch Version, CUDA version and number of GPUs you use ?

I am using torch 1.1.0 and cuda 8.0, I can  use 2GPU, both have almost 10G.

**Comment by penincillin** [comment]
Currently, we only support Pytorch 1.0. Therefore, please install Pytorch 1.0 and try again. 
Sorry for the inconvenience, support for higher version Pytorch might be updated in future.

**Comment by liwenssss** [comment]
> Currently, we only support Pytorch 1.0. Therefore, please install Pytorch 1.0 and try again.
> Sorry for the inconvenience, support for higher version Pytorch might be updated in future.

Thanks for your reply.Actually, I dont know difference between 1.0 and 1.1 . Do you feel it ok to tell me what I can do myself to support 1.1?

**Comment by penincillin** [comment]
> > Currently, we only support Pytorch 1.0. Therefore, please install Pytorch 1.0 and try again.
> > Sorry for the inconvenience, support for higher version Pytorch might be updated in future.
> 
> Thanks for your reply.Actually, I dont know difference between 1.0 and 1.1 . Do you feel it ok to tell me what I can do myself to support 1.1?

The bugs lie in the implementation of distributed training. My current implementation of distributed training only support Pytorch 1.0. Therefore, If you really want to use Pytorch 1.1. You can either choose to debug the distributed training by yourself or replace distributed training with data parallel.

**Comment by penincillin** [comment]
> > Currently, we only support Pytorch 1.0. Therefore, please install Pytorch 1.0 and try again.
> > Sorry for the inconvenience, support for higher version Pytorch might be updated in future.
> 
> Thanks for your reply.Actually, I dont know difference between 1.0 and 1.1 . Do you feel it ok to tell me what I can do myself to support 1.1?

I personally suggest you build another conda envs with Pytorch 1.0 installed. This should be the simplest way you can run the code. 
Neglecting the distributed training, there shall be no big differences between Pytorch 1.0 and Pytorch 1.1

**Comment by liwenssss** [comment]
ok , thank you

**Comment by penincillin** [comment]
@liwenssss Good news !
I fix the bugs in distributed training. Current code supports distributed training for latest version of Pytorch. (Pytorch 1.1 is also supported.)
To use the latest code, you can either pull from the repo or simply delete the following code in [src/models/dct_model.py](https://github.com/penincillin/DCT_ICCV-2019/blob/master/src/models/dct_model.py), which is located in [line 119](https://github.com/penincillin/DCT_ICCV-2019/blob/d867adcce82e6715ddcca3ad57507622f3a1623c/src/models/dct_model.py#L119) in the old code.
```
if opt.dist:
    self.smpl = DistributedDataParallel(
        self.smpl, device_ids=[torch.cuda.current_device()])
```

**Comment by liwenssss** [comment]
> @liwenssss Good news !
> I fix the bugs in distributed training. Current code supports distributed training for latest version of Pytorch. (Pytorch 1.1 is also supported.)
> To use the latest code, you can either pull from the repo or simply delete the following code in [src/models/dct_model.py](https://github.com/penincillin/DCT_ICCV-2019/blob/master/src/models/dct_model.py), which is located in [line 119](https://github.com/penincillin/DCT_ICCV-2019/blob/d867adcce82e6715ddcca3ad57507622f3a1623c/src/models/dct_model.py#L119) in the old code.
> 
> ```
> if opt.dist:
>     self.smpl = DistributedDataParallel(
>         self.smpl, device_ids=[torch.cuda.current_device()])
> ```

Thanks for your work, I try now

**Comment by liwenssss** [comment]
it's ok now! by the way, I can use opendr in python3, so I change something to support it. I am now training and will see it later.

**Comment by penincillin** [comment]
That's a really a good news ! Looking forward to hear more from you.
