### ISSUE TITLE
visualization issue

### ISSUE THREAD

**Issue by khg2478** [penincillin/DCT_ICCV-2019#5]
Hi. It seems that the source code and readme file are outdated.

visualize.sh execution for example runs util.evaluator.py file and there it loads "from smpl_webuser.serialization import load_model" but smpl_webuser doesn't exist.

There are some other problems too.

Would you fix this please?

**Comment by penincillin** [comment]
Thanks for asking. 
To resolve this problem, please download python code of smpl from [here](https://smpl.is.tue.mpg.de/) and add the code to your python search path.
