### ISSUE TITLE
Densepose Preprocessing 

### ISSUE THREAD

**Issue by dvirginz** [penincillin/DCT_ICCV-2019#7]
Hi!
Thank you very much for this repo, it is without a doubt one of the best in the field:)

Have you created the datasets yourself? (e.g densepose for human3.6 )
If so, can you please share them? It would be of tremendous help!

Thank you very much.

**Comment by penincillin** [comment]
Sorry for the late reply.
You can refer to the [detectron-2](https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose) for the latest implementation of DensePose.
