### ISSUE TITLE
Visualization  on SMPL body.

### ISSUE THREAD

**Issue by patodichayan** [penincillin/DCT_ICCV-2019#8]
How do you achieve something like Figure 3 ?! Visualise dense keypoints on SMPL body ?! Will that piece of code also work for SMPLX neutral models ?! 

[
![Screenshot from 2021-01-14 18-01-42](https://user-images.githubusercontent.com/50845663/104659457-ab0e7f00-5692-11eb-975d-098e2350cce0.png)
](url)

**Comment by penincillin** [comment]
@patodichayan I draw arrows manually using PPT. For points on SMPL, I use the [official code](https://github.com/facebookresearch/DensePose/tree/master/notebooks) provided by the DensePose team

**Comment by patodichayan** [comment]
Thanks @penincillin .
