### ISSUE TITLE
Computing DKD 

### ISSUE THREAD

**Issue by zhangy76** [penincillin/DCT_ICCV-2019#9]
Hi, 

Thanks for the interesting work. I wonder how to compute the DKD (Dense Keypoints Distance)?

Thanks,
Yufei

**Comment by penincillin** [comment]
DKD is calculated as the L2 distance between the predicted dense keypoints and the annotated dense keypoints.

**Comment by zhangy76** [comment]
Thanks for the response! Is the predicted dense keypoints computed by rendering the predicted 3D body model on the image? If that is the case, I wonder how to get the dense keypoints for a specific pixel?

**Comment by penincillin** [comment]
As for how to obtain predicted dense keypoints, you can refer to the ```section 3.1``` for the paper (subsection ```dense correspondence```)

**Comment by zhangy76** [comment]
During testing, for pixel position (x,y), we need the ground truth and prediced (I,U,V) to compute DKD. But from the predicted SMPL and camera parameters, we may only obtain the IUV for the projection of the vertices. To obtain the IUV for any visible body pixel , I wonder if you need perform any interpolation?

**Comment by penincillin** [comment]
In calculating DKD, ground truth (I, U, V) to obtain predicted pixel position (x', y'). And then compute distance between predicted and ground truth pixel position.

**Comment by zhangy76** [comment]
For table 5 in the paper, may I ask why the unit of DKD is marked as mm?

**Comment by penincillin** [comment]
@zhangy76 
Oops, unit of DKD is mm is a mistake, the unit should be pixel, please ignore that and thanks for pointing it our.

**Comment by zhangy76** [comment]
Thanks. Can I say it is the average pixel distance over pixel point in an image?

**Comment by penincillin** [comment]
Sorry for the delay reply. I cannot quite remember the details and just checked my previous code.
To calculate DKD, you should normalize the ground-truth and predicted 2D dense keypoints to lie in [-1, 1]. Then calculate l1 distance between them. Then if the magnitude does not match, then you can try to multiply some scale factor such as 10 or 1000 (Sorry, I cannot remember the detailed numbers for this, you can try first and we can have further discussion after that).
